language: node_js
node_js:
- '0.10'
before_script:
- npm install -g bower
- bower install
deploy:
  provider: npm
  email: bvdrucker@gmail.com
  api_key:
    secure: QtUOyQebWq/9EqqFxi/kxC0v8PAfNXnyGhGgE7XvoS7jgUn92tXLoZxg128XjptCEy03+QYbEYLVhS+eaLeYbqwxFb46Jtiid0y8ReELOOo78JR4EAuY2MAjcIbAZv+hkQ9wKtwz21SGluGm90j5Y5nVASZ1egv1sbNAOv1i1io=
  on:
    tags: true
    repo: bendrucker/angular-names
